// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: grpc/fuel/grpc/protos/fuel.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_ADD         TransactionType = 1
	TransactionType_TRANSACTION_TYPE_CONSUME     TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_ADD",
		2: "TRANSACTION_TYPE_CONSUME",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_ADD":         1,
		"TRANSACTION_TYPE_CONSUME":     2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_fuel_grpc_protos_fuel_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_grpc_fuel_grpc_protos_fuel_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{0}
}

type GetCurrentStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentStockRequest) Reset() {
	*x = GetCurrentStockRequest{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentStockRequest) ProtoMessage() {}

func (x *GetCurrentStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentStockRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentStockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{0}
}

type GetCurrentStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         float64                `protobuf:"fixed64,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentStockResponse) Reset() {
	*x = GetCurrentStockResponse{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentStockResponse) ProtoMessage() {}

func (x *GetCurrentStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentStockResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentStockResponse) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentStockResponse) GetStock() float64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddFuelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFuelRequest) Reset() {
	*x = AddFuelRequest{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFuelRequest) ProtoMessage() {}

func (x *AddFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFuelRequest.ProtoReflect.Descriptor instead.
func (*AddFuelRequest) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{2}
}

func (x *AddFuelRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddFuelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFuelResponse) Reset() {
	*x = AddFuelResponse{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFuelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFuelResponse) ProtoMessage() {}

func (x *AddFuelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFuelResponse.ProtoReflect.Descriptor instead.
func (*AddFuelResponse) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{3}
}

func (x *AddFuelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddFuelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsumeFuelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeFuelRequest) Reset() {
	*x = ConsumeFuelRequest{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeFuelRequest) ProtoMessage() {}

func (x *ConsumeFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeFuelRequest.ProtoReflect.Descriptor instead.
func (*ConsumeFuelRequest) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeFuelRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConsumeFuelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeFuelResponse) Reset() {
	*x = ConsumeFuelResponse{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeFuelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeFuelResponse) ProtoMessage() {}

func (x *ConsumeFuelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeFuelResponse.ProtoReflect.Descriptor instead.
func (*ConsumeFuelResponse) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeFuelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeFuelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{6}
}

type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*FuelTransaction     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*FuelTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{8}
}

func (x *CheckAvailabilityRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Stock         float64                `protobuf:"fixed64,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{9}
}

func (x *CheckAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckAvailabilityResponse) GetStock() float64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type FuelTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          TransactionType        `protobuf:"varint,2,opt,name=type,proto3,enum=fuel.TransactionType" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuelTransaction) Reset() {
	*x = FuelTransaction{}
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelTransaction) ProtoMessage() {}

func (x *FuelTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_fuel_grpc_protos_fuel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelTransaction.ProtoReflect.Descriptor instead.
func (*FuelTransaction) Descriptor() ([]byte, []int) {
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP(), []int{10}
}

func (x *FuelTransaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FuelTransaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *FuelTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FuelTransaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_grpc_fuel_grpc_protos_fuel_proto protoreflect.FileDescriptor

const file_grpc_fuel_grpc_protos_fuel_proto_rawDesc = "" +
	"\n" +
	" grpc/fuel/grpc/protos/fuel.proto\x12\x04fuel\"\x18\n" +
	"\x16GetCurrentStockRequest\"/\n" +
	"\x17GetCurrentStockResponse\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\x01R\x05stock\"(\n" +
	"\x0eAddFuelRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"E\n" +
	"\x0fAddFuelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x12ConsumeFuelRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"I\n" +
	"\x13ConsumeFuelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1e\n" +
	"\x1cGetTransactionHistoryRequest\"Z\n" +
	"\x1dGetTransactionHistoryResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.fuel.FuelTransactionR\ftransactions\"2\n" +
	"\x18CheckAvailabilityRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"O\n" +
	"\x19CheckAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x01R\x05stock\"\x82\x01\n" +
	"\x0fFuelTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.fuel.TransactionTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp*k\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRANSACTION_TYPE_ADD\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_CONSUME\x10\x022\x91\x03\n" +
	"\vFuelService\x12N\n" +
	"\x0fGetCurrentStock\x12\x1c.fuel.GetCurrentStockRequest\x1a\x1d.fuel.GetCurrentStockResponse\x126\n" +
	"\aAddFuel\x12\x14.fuel.AddFuelRequest\x1a\x15.fuel.AddFuelResponse\x12B\n" +
	"\vConsumeFuel\x12\x18.fuel.ConsumeFuelRequest\x1a\x19.fuel.ConsumeFuelResponse\x12`\n" +
	"\x15GetTransactionHistory\x12\".fuel.GetTransactionHistoryRequest\x1a#.fuel.GetTransactionHistoryResponse\x12T\n" +
	"\x11CheckAvailability\x12\x1e.fuel.CheckAvailabilityRequest\x1a\x1f.fuel.CheckAvailabilityResponseB\x1fZ\x1dastrogo/grpc/fuel/grpc/protosb\x06proto3"

var (
	file_grpc_fuel_grpc_protos_fuel_proto_rawDescOnce sync.Once
	file_grpc_fuel_grpc_protos_fuel_proto_rawDescData []byte
)

func file_grpc_fuel_grpc_protos_fuel_proto_rawDescGZIP() []byte {
	file_grpc_fuel_grpc_protos_fuel_proto_rawDescOnce.Do(func() {
		file_grpc_fuel_grpc_protos_fuel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_fuel_grpc_protos_fuel_proto_rawDesc), len(file_grpc_fuel_grpc_protos_fuel_proto_rawDesc)))
	})
	return file_grpc_fuel_grpc_protos_fuel_proto_rawDescData
}

var file_grpc_fuel_grpc_protos_fuel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_fuel_grpc_protos_fuel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_fuel_grpc_protos_fuel_proto_goTypes = []any{
	(TransactionType)(0),                  // 0: fuel.TransactionType
	(*GetCurrentStockRequest)(nil),        // 1: fuel.GetCurrentStockRequest
	(*GetCurrentStockResponse)(nil),       // 2: fuel.GetCurrentStockResponse
	(*AddFuelRequest)(nil),                // 3: fuel.AddFuelRequest
	(*AddFuelResponse)(nil),               // 4: fuel.AddFuelResponse
	(*ConsumeFuelRequest)(nil),            // 5: fuel.ConsumeFuelRequest
	(*ConsumeFuelResponse)(nil),           // 6: fuel.ConsumeFuelResponse
	(*GetTransactionHistoryRequest)(nil),  // 7: fuel.GetTransactionHistoryRequest
	(*GetTransactionHistoryResponse)(nil), // 8: fuel.GetTransactionHistoryResponse
	(*CheckAvailabilityRequest)(nil),      // 9: fuel.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),     // 10: fuel.CheckAvailabilityResponse
	(*FuelTransaction)(nil),               // 11: fuel.FuelTransaction
}
var file_grpc_fuel_grpc_protos_fuel_proto_depIdxs = []int32{
	11, // 0: fuel.GetTransactionHistoryResponse.transactions:type_name -> fuel.FuelTransaction
	0,  // 1: fuel.FuelTransaction.type:type_name -> fuel.TransactionType
	1,  // 2: fuel.FuelService.GetCurrentStock:input_type -> fuel.GetCurrentStockRequest
	3,  // 3: fuel.FuelService.AddFuel:input_type -> fuel.AddFuelRequest
	5,  // 4: fuel.FuelService.ConsumeFuel:input_type -> fuel.ConsumeFuelRequest
	7,  // 5: fuel.FuelService.GetTransactionHistory:input_type -> fuel.GetTransactionHistoryRequest
	9,  // 6: fuel.FuelService.CheckAvailability:input_type -> fuel.CheckAvailabilityRequest
	2,  // 7: fuel.FuelService.GetCurrentStock:output_type -> fuel.GetCurrentStockResponse
	4,  // 8: fuel.FuelService.AddFuel:output_type -> fuel.AddFuelResponse
	6,  // 9: fuel.FuelService.ConsumeFuel:output_type -> fuel.ConsumeFuelResponse
	8,  // 10: fuel.FuelService.GetTransactionHistory:output_type -> fuel.GetTransactionHistoryResponse
	10, // 11: fuel.FuelService.CheckAvailability:output_type -> fuel.CheckAvailabilityResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_fuel_grpc_protos_fuel_proto_init() }
func file_grpc_fuel_grpc_protos_fuel_proto_init() {
	if File_grpc_fuel_grpc_protos_fuel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_fuel_grpc_protos_fuel_proto_rawDesc), len(file_grpc_fuel_grpc_protos_fuel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_fuel_grpc_protos_fuel_proto_goTypes,
		DependencyIndexes: file_grpc_fuel_grpc_protos_fuel_proto_depIdxs,
		EnumInfos:         file_grpc_fuel_grpc_protos_fuel_proto_enumTypes,
		MessageInfos:      file_grpc_fuel_grpc_protos_fuel_proto_msgTypes,
	}.Build()
	File_grpc_fuel_grpc_protos_fuel_proto = out.File
	file_grpc_fuel_grpc_protos_fuel_proto_goTypes = nil
	file_grpc_fuel_grpc_protos_fuel_proto_depIdxs = nil
}
