// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: grpc/protos/mission.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mission types
type MissionType int32

const (
	MissionType_MISSION_TYPE_EXPLORATION MissionType = 0
	MissionType_MISSION_TYPE_RESEARCH    MissionType = 1
	MissionType_MISSION_TYPE_MAINTENANCE MissionType = 2
	MissionType_MISSION_TYPE_TRANSPORT   MissionType = 3
)

// Enum value maps for MissionType.
var (
	MissionType_name = map[int32]string{
		0: "MISSION_TYPE_EXPLORATION",
		1: "MISSION_TYPE_RESEARCH",
		2: "MISSION_TYPE_MAINTENANCE",
		3: "MISSION_TYPE_TRANSPORT",
	}
	MissionType_value = map[string]int32{
		"MISSION_TYPE_EXPLORATION": 0,
		"MISSION_TYPE_RESEARCH":    1,
		"MISSION_TYPE_MAINTENANCE": 2,
		"MISSION_TYPE_TRANSPORT":   3,
	}
)

func (x MissionType) Enum() *MissionType {
	p := new(MissionType)
	*p = x
	return p
}

func (x MissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_protos_mission_proto_enumTypes[0].Descriptor()
}

func (MissionType) Type() protoreflect.EnumType {
	return &file_grpc_protos_mission_proto_enumTypes[0]
}

func (x MissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissionType.Descriptor instead.
func (MissionType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{0}
}

// Mission statuses
type MissionStatus int32

const (
	MissionStatus_MISSION_STATUS_PENDING     MissionStatus = 0
	MissionStatus_MISSION_STATUS_IN_PROGRESS MissionStatus = 1
	MissionStatus_MISSION_STATUS_COMPLETED   MissionStatus = 2
	MissionStatus_MISSION_STATUS_FAILED      MissionStatus = 3
)

// Enum value maps for MissionStatus.
var (
	MissionStatus_name = map[int32]string{
		0: "MISSION_STATUS_PENDING",
		1: "MISSION_STATUS_IN_PROGRESS",
		2: "MISSION_STATUS_COMPLETED",
		3: "MISSION_STATUS_FAILED",
	}
	MissionStatus_value = map[string]int32{
		"MISSION_STATUS_PENDING":     0,
		"MISSION_STATUS_IN_PROGRESS": 1,
		"MISSION_STATUS_COMPLETED":   2,
		"MISSION_STATUS_FAILED":      3,
	}
)

func (x MissionStatus) Enum() *MissionStatus {
	p := new(MissionStatus)
	*p = x
	return p
}

func (x MissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_protos_mission_proto_enumTypes[1].Descriptor()
}

func (MissionStatus) Type() protoreflect.EnumType {
	return &file_grpc_protos_mission_proto_enumTypes[1]
}

func (x MissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissionStatus.Descriptor instead.
func (MissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{1}
}

// Mission resource requirements
type MissionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyAmount  float64                `protobuf:"fixed64,1,opt,name=energy_amount,json=energyAmount,proto3" json:"energy_amount,omitempty"` // kWh
	FuelAmount    float64                `protobuf:"fixed64,2,opt,name=fuel_amount,json=fuelAmount,proto3" json:"fuel_amount,omitempty"`       // L
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionResource) Reset() {
	*x = MissionResource{}
	mi := &file_grpc_protos_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResource) ProtoMessage() {}

func (x *MissionResource) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResource.ProtoReflect.Descriptor instead.
func (*MissionResource) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{0}
}

func (x *MissionResource) GetEnergyAmount() float64 {
	if x != nil {
		return x.EnergyAmount
	}
	return 0
}

func (x *MissionResource) GetFuelAmount() float64 {
	if x != nil {
		return x.FuelAmount
	}
	return 0
}

// Mission message
type Mission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          MissionType            `protobuf:"varint,4,opt,name=type,proto3,enum=mission.MissionType" json:"type,omitempty"`
	Status        MissionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=mission.MissionStatus" json:"status,omitempty"`
	EnergyReq     float64                `protobuf:"fixed64,6,opt,name=energy_req,json=energyReq,proto3" json:"energy_req,omitempty"`      // kWh
	FuelReq       float64                `protobuf:"fixed64,7,opt,name=fuel_req,json=fuelReq,proto3" json:"fuel_req,omitempty"`            // L
	AstronautId   uint64                 `protobuf:"varint,8,opt,name=astronaut_id,json=astronautId,proto3" json:"astronaut_id,omitempty"` // Optional
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt     string                 `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`             // Optional
	CompletedAt   string                 `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`       // Optional
	FailedAt      string                 `protobuf:"bytes,13,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`                // Optional
	FailureReason string                 `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mission) Reset() {
	*x = Mission{}
	mi := &file_grpc_protos_mission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{1}
}

func (x *Mission) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission) GetType() MissionType {
	if x != nil {
		return x.Type
	}
	return MissionType_MISSION_TYPE_EXPLORATION
}

func (x *Mission) GetStatus() MissionStatus {
	if x != nil {
		return x.Status
	}
	return MissionStatus_MISSION_STATUS_PENDING
}

func (x *Mission) GetEnergyReq() float64 {
	if x != nil {
		return x.EnergyReq
	}
	return 0
}

func (x *Mission) GetFuelReq() float64 {
	if x != nil {
		return x.FuelReq
	}
	return 0
}

func (x *Mission) GetAstronautId() uint64 {
	if x != nil {
		return x.AstronautId
	}
	return 0
}

func (x *Mission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Mission) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Mission) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Mission) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Mission) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *Mission) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// Create mission request
type CreateMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          MissionType            `protobuf:"varint,3,opt,name=type,proto3,enum=mission.MissionType" json:"type,omitempty"`
	EnergyReq     float64                `protobuf:"fixed64,4,opt,name=energy_req,json=energyReq,proto3" json:"energy_req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMissionRequest) Reset() {
	*x = CreateMissionRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMissionRequest) ProtoMessage() {}

func (x *CreateMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMissionRequest.ProtoReflect.Descriptor instead.
func (*CreateMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMissionRequest) GetType() MissionType {
	if x != nil {
		return x.Type
	}
	return MissionType_MISSION_TYPE_EXPLORATION
}

func (x *CreateMissionRequest) GetEnergyReq() float64 {
	if x != nil {
		return x.EnergyReq
	}
	return 0
}

// Create mission response
type CreateMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMissionResponse) Reset() {
	*x = CreateMissionResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMissionResponse) ProtoMessage() {}

func (x *CreateMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMissionResponse.ProtoReflect.Descriptor instead.
func (*CreateMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMissionResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

// Get mission request
type GetMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionRequest) Reset() {
	*x = GetMissionRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionRequest) ProtoMessage() {}

func (x *GetMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionRequest.ProtoReflect.Descriptor instead.
func (*GetMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{4}
}

func (x *GetMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

// Get mission response
type GetMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionResponse) Reset() {
	*x = GetMissionResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionResponse) ProtoMessage() {}

func (x *GetMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionResponse.ProtoReflect.Descriptor instead.
func (*GetMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{5}
}

func (x *GetMissionResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

// List missions request
type ListMissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MissionStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=mission.MissionStatus" json:"status,omitempty"` // Optional
	Type          MissionType            `protobuf:"varint,2,opt,name=type,proto3,enum=mission.MissionType" json:"type,omitempty"`       // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsRequest) Reset() {
	*x = ListMissionsRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsRequest) ProtoMessage() {}

func (x *ListMissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsRequest.ProtoReflect.Descriptor instead.
func (*ListMissionsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{6}
}

func (x *ListMissionsRequest) GetStatus() MissionStatus {
	if x != nil {
		return x.Status
	}
	return MissionStatus_MISSION_STATUS_PENDING
}

func (x *ListMissionsRequest) GetType() MissionType {
	if x != nil {
		return x.Type
	}
	return MissionType_MISSION_TYPE_EXPLORATION
}

// List missions response
type ListMissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missions      []*Mission             `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsResponse) Reset() {
	*x = ListMissionsResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsResponse) ProtoMessage() {}

func (x *ListMissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsResponse.ProtoReflect.Descriptor instead.
func (*ListMissionsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{7}
}

func (x *ListMissionsResponse) GetMissions() []*Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

// Start mission request
type StartMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMissionRequest) Reset() {
	*x = StartMissionRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMissionRequest) ProtoMessage() {}

func (x *StartMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMissionRequest.ProtoReflect.Descriptor instead.
func (*StartMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{8}
}

func (x *StartMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

// Start mission response
type StartMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMissionResponse) Reset() {
	*x = StartMissionResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMissionResponse) ProtoMessage() {}

func (x *StartMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMissionResponse.ProtoReflect.Descriptor instead.
func (*StartMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{9}
}

func (x *StartMissionResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

// Complete mission request
type CompleteMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMissionRequest) Reset() {
	*x = CompleteMissionRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMissionRequest) ProtoMessage() {}

func (x *CompleteMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMissionRequest.ProtoReflect.Descriptor instead.
func (*CompleteMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

// Complete mission response
type CompleteMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMissionResponse) Reset() {
	*x = CompleteMissionResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMissionResponse) ProtoMessage() {}

func (x *CompleteMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMissionResponse.ProtoReflect.Descriptor instead.
func (*CompleteMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteMissionResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

// Fail mission request
type FailMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailMissionRequest) Reset() {
	*x = FailMissionRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailMissionRequest) ProtoMessage() {}

func (x *FailMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailMissionRequest.ProtoReflect.Descriptor instead.
func (*FailMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{12}
}

func (x *FailMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

func (x *FailMissionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Fail mission response
type FailMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailMissionResponse) Reset() {
	*x = FailMissionResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailMissionResponse) ProtoMessage() {}

func (x *FailMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailMissionResponse.ProtoReflect.Descriptor instead.
func (*FailMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{13}
}

func (x *FailMissionResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

// Assign astronaut request
type AssignAstronautRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	AstronautId   uint64                 `protobuf:"varint,2,opt,name=astronaut_id,json=astronautId,proto3" json:"astronaut_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAstronautRequest) Reset() {
	*x = AssignAstronautRequest{}
	mi := &file_grpc_protos_mission_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAstronautRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAstronautRequest) ProtoMessage() {}

func (x *AssignAstronautRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAstronautRequest.ProtoReflect.Descriptor instead.
func (*AssignAstronautRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{14}
}

func (x *AssignAstronautRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

func (x *AssignAstronautRequest) GetAstronautId() uint64 {
	if x != nil {
		return x.AstronautId
	}
	return 0
}

// Assign astronaut response
type AssignAstronautResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAstronautResponse) Reset() {
	*x = AssignAstronautResponse{}
	mi := &file_grpc_protos_mission_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAstronautResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAstronautResponse) ProtoMessage() {}

func (x *AssignAstronautResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_mission_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAstronautResponse.ProtoReflect.Descriptor instead.
func (*AssignAstronautResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_mission_proto_rawDescGZIP(), []int{15}
}

func (x *AssignAstronautResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

var File_grpc_protos_mission_proto protoreflect.FileDescriptor

const file_grpc_protos_mission_proto_rawDesc = "" +
	"\n" +
	"\x19grpc/protos/mission.proto\x12\amission\"W\n" +
	"\x0fMissionResource\x12#\n" +
	"\renergy_amount\x18\x01 \x01(\x01R\fenergyAmount\x12\x1f\n" +
	"\vfuel_amount\x18\x02 \x01(\x01R\n" +
	"fuelAmount\"\xca\x03\n" +
	"\aMission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.mission.MissionTypeR\x04type\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.mission.MissionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"energy_req\x18\x06 \x01(\x01R\tenergyReq\x12\x19\n" +
	"\bfuel_req\x18\a \x01(\x01R\afuelReq\x12!\n" +
	"\fastronaut_id\x18\b \x01(\x04R\vastronautId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\tR\vcompletedAt\x12\x1b\n" +
	"\tfailed_at\x18\r \x01(\tR\bfailedAt\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\"\x95\x01\n" +
	"\x14CreateMissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.mission.MissionTypeR\x04type\x12\x1d\n" +
	"\n" +
	"energy_req\x18\x04 \x01(\x01R\tenergyReq\"C\n" +
	"\x15CreateMissionResponse\x12*\n" +
	"\amission\x18\x01 \x01(\v2\x10.mission.MissionR\amission\"2\n" +
	"\x11GetMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"@\n" +
	"\x12GetMissionResponse\x12*\n" +
	"\amission\x18\x01 \x01(\v2\x10.mission.MissionR\amission\"o\n" +
	"\x13ListMissionsRequest\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.mission.MissionStatusR\x06status\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.mission.MissionTypeR\x04type\"D\n" +
	"\x14ListMissionsResponse\x12,\n" +
	"\bmissions\x18\x01 \x03(\v2\x10.mission.MissionR\bmissions\"4\n" +
	"\x13StartMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"B\n" +
	"\x14StartMissionResponse\x12*\n" +
	"\amission\x18\x01 \x01(\v2\x10.mission.MissionR\amission\"7\n" +
	"\x16CompleteMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"E\n" +
	"\x17CompleteMissionResponse\x12*\n" +
	"\amission\x18\x01 \x01(\v2\x10.mission.MissionR\amission\"K\n" +
	"\x12FailMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"A\n" +
	"\x13FailMissionResponse\x12*\n" +
	"\amission\x18\x01 \x01(\v2\x10.mission.MissionR\amission\"Z\n" +
	"\x16AssignAstronautRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\x12!\n" +
	"\fastronaut_id\x18\x02 \x01(\x04R\vastronautId\"E\n" +
	"\x17AssignAstronautResponse\x12*\n" +
	"\amission\x18\x01 \x01(\v2\x10.mission.MissionR\amission*\x80\x01\n" +
	"\vMissionType\x12\x1c\n" +
	"\x18MISSION_TYPE_EXPLORATION\x10\x00\x12\x19\n" +
	"\x15MISSION_TYPE_RESEARCH\x10\x01\x12\x1c\n" +
	"\x18MISSION_TYPE_MAINTENANCE\x10\x02\x12\x1a\n" +
	"\x16MISSION_TYPE_TRANSPORT\x10\x03*\x84\x01\n" +
	"\rMissionStatus\x12\x1a\n" +
	"\x16MISSION_STATUS_PENDING\x10\x00\x12\x1e\n" +
	"\x1aMISSION_STATUS_IN_PROGRESS\x10\x01\x12\x1c\n" +
	"\x18MISSION_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15MISSION_STATUS_FAILED\x10\x032\xb7\x04\n" +
	"\x0eMissionService\x12N\n" +
	"\rCreateMission\x12\x1d.mission.CreateMissionRequest\x1a\x1e.mission.CreateMissionResponse\x12E\n" +
	"\n" +
	"GetMission\x12\x1a.mission.GetMissionRequest\x1a\x1b.mission.GetMissionResponse\x12K\n" +
	"\fListMissions\x12\x1c.mission.ListMissionsRequest\x1a\x1d.mission.ListMissionsResponse\x12K\n" +
	"\fStartMission\x12\x1c.mission.StartMissionRequest\x1a\x1d.mission.StartMissionResponse\x12T\n" +
	"\x0fCompleteMission\x12\x1f.mission.CompleteMissionRequest\x1a .mission.CompleteMissionResponse\x12H\n" +
	"\vFailMission\x12\x1b.mission.FailMissionRequest\x1a\x1c.mission.FailMissionResponse\x12T\n" +
	"\x0fAssignAstronaut\x12\x1f.mission.AssignAstronautRequest\x1a .mission.AssignAstronautResponseB\"Z astrogo/grpc/mission/grpc/protosb\x06proto3"

var (
	file_grpc_protos_mission_proto_rawDescOnce sync.Once
	file_grpc_protos_mission_proto_rawDescData []byte
)

func file_grpc_protos_mission_proto_rawDescGZIP() []byte {
	file_grpc_protos_mission_proto_rawDescOnce.Do(func() {
		file_grpc_protos_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_protos_mission_proto_rawDesc), len(file_grpc_protos_mission_proto_rawDesc)))
	})
	return file_grpc_protos_mission_proto_rawDescData
}

var file_grpc_protos_mission_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_protos_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_grpc_protos_mission_proto_goTypes = []any{
	(MissionType)(0),                // 0: mission.MissionType
	(MissionStatus)(0),              // 1: mission.MissionStatus
	(*MissionResource)(nil),         // 2: mission.MissionResource
	(*Mission)(nil),                 // 3: mission.Mission
	(*CreateMissionRequest)(nil),    // 4: mission.CreateMissionRequest
	(*CreateMissionResponse)(nil),   // 5: mission.CreateMissionResponse
	(*GetMissionRequest)(nil),       // 6: mission.GetMissionRequest
	(*GetMissionResponse)(nil),      // 7: mission.GetMissionResponse
	(*ListMissionsRequest)(nil),     // 8: mission.ListMissionsRequest
	(*ListMissionsResponse)(nil),    // 9: mission.ListMissionsResponse
	(*StartMissionRequest)(nil),     // 10: mission.StartMissionRequest
	(*StartMissionResponse)(nil),    // 11: mission.StartMissionResponse
	(*CompleteMissionRequest)(nil),  // 12: mission.CompleteMissionRequest
	(*CompleteMissionResponse)(nil), // 13: mission.CompleteMissionResponse
	(*FailMissionRequest)(nil),      // 14: mission.FailMissionRequest
	(*FailMissionResponse)(nil),     // 15: mission.FailMissionResponse
	(*AssignAstronautRequest)(nil),  // 16: mission.AssignAstronautRequest
	(*AssignAstronautResponse)(nil), // 17: mission.AssignAstronautResponse
}
var file_grpc_protos_mission_proto_depIdxs = []int32{
	0,  // 0: mission.Mission.type:type_name -> mission.MissionType
	1,  // 1: mission.Mission.status:type_name -> mission.MissionStatus
	0,  // 2: mission.CreateMissionRequest.type:type_name -> mission.MissionType
	3,  // 3: mission.CreateMissionResponse.mission:type_name -> mission.Mission
	3,  // 4: mission.GetMissionResponse.mission:type_name -> mission.Mission
	1,  // 5: mission.ListMissionsRequest.status:type_name -> mission.MissionStatus
	0,  // 6: mission.ListMissionsRequest.type:type_name -> mission.MissionType
	3,  // 7: mission.ListMissionsResponse.missions:type_name -> mission.Mission
	3,  // 8: mission.StartMissionResponse.mission:type_name -> mission.Mission
	3,  // 9: mission.CompleteMissionResponse.mission:type_name -> mission.Mission
	3,  // 10: mission.FailMissionResponse.mission:type_name -> mission.Mission
	3,  // 11: mission.AssignAstronautResponse.mission:type_name -> mission.Mission
	4,  // 12: mission.MissionService.CreateMission:input_type -> mission.CreateMissionRequest
	6,  // 13: mission.MissionService.GetMission:input_type -> mission.GetMissionRequest
	8,  // 14: mission.MissionService.ListMissions:input_type -> mission.ListMissionsRequest
	10, // 15: mission.MissionService.StartMission:input_type -> mission.StartMissionRequest
	12, // 16: mission.MissionService.CompleteMission:input_type -> mission.CompleteMissionRequest
	14, // 17: mission.MissionService.FailMission:input_type -> mission.FailMissionRequest
	16, // 18: mission.MissionService.AssignAstronaut:input_type -> mission.AssignAstronautRequest
	5,  // 19: mission.MissionService.CreateMission:output_type -> mission.CreateMissionResponse
	7,  // 20: mission.MissionService.GetMission:output_type -> mission.GetMissionResponse
	9,  // 21: mission.MissionService.ListMissions:output_type -> mission.ListMissionsResponse
	11, // 22: mission.MissionService.StartMission:output_type -> mission.StartMissionResponse
	13, // 23: mission.MissionService.CompleteMission:output_type -> mission.CompleteMissionResponse
	15, // 24: mission.MissionService.FailMission:output_type -> mission.FailMissionResponse
	17, // 25: mission.MissionService.AssignAstronaut:output_type -> mission.AssignAstronautResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_grpc_protos_mission_proto_init() }
func file_grpc_protos_mission_proto_init() {
	if File_grpc_protos_mission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_protos_mission_proto_rawDesc), len(file_grpc_protos_mission_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protos_mission_proto_goTypes,
		DependencyIndexes: file_grpc_protos_mission_proto_depIdxs,
		EnumInfos:         file_grpc_protos_mission_proto_enumTypes,
		MessageInfos:      file_grpc_protos_mission_proto_msgTypes,
	}.Build()
	File_grpc_protos_mission_proto = out.File
	file_grpc_protos_mission_proto_goTypes = nil
	file_grpc_protos_mission_proto_depIdxs = nil
}
