apiVersion: v1
kind: Service
metadata:
  name: fuel-service
  namespace: astrogo
spec:
  selector:
    app: fuel-service
  ports:
  - name: grpc
    port: 8087
    targetPort: 8087
  - name: http
    port: 8088
    targetPort: 8088 