apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: astrogo
spec:
  selector:
    app: kafka
  ports:
  - name: external
    port: 9092
    targetPort: 9092
  - name: internal
    port: 29092
    targetPort: 29092
  clusterIP: None  # Headless service for StatefulSet 