apiVersion: v1
kind: Service
metadata:
  name: energy-service
  namespace: astrogo
spec:
  selector:
    app: energy-service
  ports:
  - name: grpc
    port: 8083
    targetPort: 8083
  - name: http
    port: 8085
    targetPort: 8085 