apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: astrogo
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
  clusterIP: None  # Headless service for StatefulSet 