apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: astrogo
data:
  POSTGRES_MULTIPLE_DATABASES: "astronautdb,energydb,fueldb,missiondb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432" 