// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: grpc/protos/energy.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Energy transaction types
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_ADDITION    TransactionType = 0
	TransactionType_TRANSACTION_TYPE_CONSUMPTION TransactionType = 1
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_ADDITION",
		1: "TRANSACTION_TYPE_CONSUMPTION",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_ADDITION":    0,
		"TRANSACTION_TYPE_CONSUMPTION": 1,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_protos_energy_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_grpc_protos_energy_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{0}
}

// Energy stock message
type EnergyStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"` // kWh
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnergyStock) Reset() {
	*x = EnergyStock{}
	mi := &file_grpc_protos_energy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyStock) ProtoMessage() {}

func (x *EnergyStock) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyStock.ProtoReflect.Descriptor instead.
func (*EnergyStock) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{0}
}

func (x *EnergyStock) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnergyStock) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EnergyStock) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Energy transaction message
type EnergyTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"` // kWh
	Type          TransactionType        `protobuf:"varint,3,opt,name=type,proto3,enum=energy.TransactionType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnergyTransaction) Reset() {
	*x = EnergyTransaction{}
	mi := &file_grpc_protos_energy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyTransaction) ProtoMessage() {}

func (x *EnergyTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyTransaction.ProtoReflect.Descriptor instead.
func (*EnergyTransaction) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{1}
}

func (x *EnergyTransaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnergyTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EnergyTransaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_ADDITION
}

func (x *EnergyTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EnergyTransaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Get current stock request
type GetCurrentStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentStockRequest) Reset() {
	*x = GetCurrentStockRequest{}
	mi := &file_grpc_protos_energy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentStockRequest) ProtoMessage() {}

func (x *GetCurrentStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentStockRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentStockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{2}
}

// Get current stock response
type GetCurrentStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentStockResponse) Reset() {
	*x = GetCurrentStockResponse{}
	mi := &file_grpc_protos_energy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentStockResponse) ProtoMessage() {}

func (x *GetCurrentStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentStockResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentStockResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentStockResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Add energy request
type AddEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"` // kWh
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEnergyRequest) Reset() {
	*x = AddEnergyRequest{}
	mi := &file_grpc_protos_energy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEnergyRequest) ProtoMessage() {}

func (x *AddEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEnergyRequest.ProtoReflect.Descriptor instead.
func (*AddEnergyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{4}
}

func (x *AddEnergyRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddEnergyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Add energy response
type AddEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEnergyResponse) Reset() {
	*x = AddEnergyResponse{}
	mi := &file_grpc_protos_energy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEnergyResponse) ProtoMessage() {}

func (x *AddEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEnergyResponse.ProtoReflect.Descriptor instead.
func (*AddEnergyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{5}
}

func (x *AddEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Consume energy request
type ConsumeEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"` // kWh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeEnergyRequest) Reset() {
	*x = ConsumeEnergyRequest{}
	mi := &file_grpc_protos_energy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyRequest) ProtoMessage() {}

func (x *ConsumeEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyRequest.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumeEnergyRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Consume energy response
type ConsumeEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeEnergyResponse) Reset() {
	*x = ConsumeEnergyResponse{}
	mi := &file_grpc_protos_energy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyResponse) ProtoMessage() {}

func (x *ConsumeEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyResponse.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumeEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get transaction history request
type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Maximum number of transactions to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_grpc_protos_energy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Get transaction history response
type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*EnergyTransaction   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_grpc_protos_energy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*EnergyTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Check availability request
type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"` // kWh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_grpc_protos_energy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{10}
}

func (x *CheckAvailabilityRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Check availability response
type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_grpc_protos_energy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_energy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_energy_proto_rawDescGZIP(), []int{11}
}

func (x *CheckAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_grpc_protos_energy_proto protoreflect.FileDescriptor

const file_grpc_protos_energy_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/protos/energy.proto\x12\x06energy\"T\n" +
	"\vEnergyStock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"\xa9\x01\n" +
	"\x11EnergyTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.energy.TransactionTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x18\n" +
	"\x16GetCurrentStockRequest\"1\n" +
	"\x17GetCurrentStockResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"L\n" +
	"\x10AddEnergyRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"-\n" +
	"\x11AddEnergyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x14ConsumeEnergyRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"1\n" +
	"\x15ConsumeEnergyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x1cGetTransactionHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"^\n" +
	"\x1dGetTransactionHistoryResponse\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.energy.EnergyTransactionR\ftransactions\"2\n" +
	"\x18CheckAvailabilityRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"9\n" +
	"\x19CheckAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable*R\n" +
	"\x0fTransactionType\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_ADDITION\x10\x00\x12 \n" +
	"\x1cTRANSACTION_TYPE_CONSUMPTION\x10\x012\xb3\x03\n" +
	"\rEnergyService\x12R\n" +
	"\x0fGetCurrentStock\x12\x1e.energy.GetCurrentStockRequest\x1a\x1f.energy.GetCurrentStockResponse\x12@\n" +
	"\tAddEnergy\x12\x18.energy.AddEnergyRequest\x1a\x19.energy.AddEnergyResponse\x12L\n" +
	"\rConsumeEnergy\x12\x1c.energy.ConsumeEnergyRequest\x1a\x1d.energy.ConsumeEnergyResponse\x12d\n" +
	"\x15GetTransactionHistory\x12$.energy.GetTransactionHistoryRequest\x1a%.energy.GetTransactionHistoryResponse\x12X\n" +
	"\x11CheckAvailability\x12 .energy.CheckAvailabilityRequest\x1a!.energy.CheckAvailabilityResponseB!Z\x1fastrogo/grpc/energy/grpc/protosb\x06proto3"

var (
	file_grpc_protos_energy_proto_rawDescOnce sync.Once
	file_grpc_protos_energy_proto_rawDescData []byte
)

func file_grpc_protos_energy_proto_rawDescGZIP() []byte {
	file_grpc_protos_energy_proto_rawDescOnce.Do(func() {
		file_grpc_protos_energy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_protos_energy_proto_rawDesc), len(file_grpc_protos_energy_proto_rawDesc)))
	})
	return file_grpc_protos_energy_proto_rawDescData
}

var file_grpc_protos_energy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_protos_energy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_grpc_protos_energy_proto_goTypes = []any{
	(TransactionType)(0),                  // 0: energy.TransactionType
	(*EnergyStock)(nil),                   // 1: energy.EnergyStock
	(*EnergyTransaction)(nil),             // 2: energy.EnergyTransaction
	(*GetCurrentStockRequest)(nil),        // 3: energy.GetCurrentStockRequest
	(*GetCurrentStockResponse)(nil),       // 4: energy.GetCurrentStockResponse
	(*AddEnergyRequest)(nil),              // 5: energy.AddEnergyRequest
	(*AddEnergyResponse)(nil),             // 6: energy.AddEnergyResponse
	(*ConsumeEnergyRequest)(nil),          // 7: energy.ConsumeEnergyRequest
	(*ConsumeEnergyResponse)(nil),         // 8: energy.ConsumeEnergyResponse
	(*GetTransactionHistoryRequest)(nil),  // 9: energy.GetTransactionHistoryRequest
	(*GetTransactionHistoryResponse)(nil), // 10: energy.GetTransactionHistoryResponse
	(*CheckAvailabilityRequest)(nil),      // 11: energy.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),     // 12: energy.CheckAvailabilityResponse
}
var file_grpc_protos_energy_proto_depIdxs = []int32{
	0,  // 0: energy.EnergyTransaction.type:type_name -> energy.TransactionType
	2,  // 1: energy.GetTransactionHistoryResponse.transactions:type_name -> energy.EnergyTransaction
	3,  // 2: energy.EnergyService.GetCurrentStock:input_type -> energy.GetCurrentStockRequest
	5,  // 3: energy.EnergyService.AddEnergy:input_type -> energy.AddEnergyRequest
	7,  // 4: energy.EnergyService.ConsumeEnergy:input_type -> energy.ConsumeEnergyRequest
	9,  // 5: energy.EnergyService.GetTransactionHistory:input_type -> energy.GetTransactionHistoryRequest
	11, // 6: energy.EnergyService.CheckAvailability:input_type -> energy.CheckAvailabilityRequest
	4,  // 7: energy.EnergyService.GetCurrentStock:output_type -> energy.GetCurrentStockResponse
	6,  // 8: energy.EnergyService.AddEnergy:output_type -> energy.AddEnergyResponse
	8,  // 9: energy.EnergyService.ConsumeEnergy:output_type -> energy.ConsumeEnergyResponse
	10, // 10: energy.EnergyService.GetTransactionHistory:output_type -> energy.GetTransactionHistoryResponse
	12, // 11: energy.EnergyService.CheckAvailability:output_type -> energy.CheckAvailabilityResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_protos_energy_proto_init() }
func file_grpc_protos_energy_proto_init() {
	if File_grpc_protos_energy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_protos_energy_proto_rawDesc), len(file_grpc_protos_energy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protos_energy_proto_goTypes,
		DependencyIndexes: file_grpc_protos_energy_proto_depIdxs,
		EnumInfos:         file_grpc_protos_energy_proto_enumTypes,
		MessageInfos:      file_grpc_protos_energy_proto_msgTypes,
	}.Build()
	File_grpc_protos_energy_proto = out.File
	file_grpc_protos_energy_proto_goTypes = nil
	file_grpc_protos_energy_proto_depIdxs = nil
}
